- hosts: api
  user: deploy
  sudo: true
  tasks:
    - name: Install Gem Prerequisites
      apt: pkg={{ item }} state=installed
      with_items:
        - libpq-dev
        - nodejs

- hosts: api
  user: deploy
  sudo: true
  vars_files:
    - vars/db.yml
    - vars/nginx.yml
    - vars/repository.yml
    - vars/rails.yml
    - vars/hipchat.yml
    - vars/consul.yml

  roles:

    # Setup environment variables inside consul
    - { role: consul_set, key: "greens/postcode/db/username",       value: "{{ db.username }}" }
    - { role: consul_set, key: "greens/postcode/db/password",       value: "{{ db.password }}" }
    - { role: consul_set, key: "greens/postcode/db/name",           value: "{{ db.name     }}" }
    - { role: consul_set, key: "greens/postcode/secret_key_base",   value: "{{ rails.environment_variables.SECRET_KEY_BASE }}" }
    - { role: consul_set, key: "greens/postcode/devise/secret_key", value: "{{ rails.environment_variables.DEVISE_SECRET_KEY }}" }

    # Clone latest version of repository
    - { role: repository_pull }

    # Run Setup common to most Rails apps
    - { role: rails }

    # Install Unicorn init scripts
    - { role: unicorn }

    # Install Sidekiq worker init scripts
    - { role: sidekiq }

    # Install Nginx config
    - { role: nginx }

    # Install RPush Daemon
    - { role: rpush }

    # Setup a service for consul (to be used by ha_proxy)
    - { role: consul_service, consul_services: { name: "t5", tags: [], port: 80, interval: "10s", type: "rails" } }
    - { role: consul_service, consul_services: { name: "t5", tags: [], interval: "10s", type: "sidekiq"         } }

    # Done!
    #- { role: hipchat_announce, room: "engineering", colour: "green", message: "Deployed FarmGeek Web API" }

