default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: postcode_lookup_development

test:
  <<: *default
  database: postcode_lookup_test

production:
  <<: *default
  database: postcode_lookup_production
  username: postcode_lookup
  password: <%= ENV['POSTCODE_LOOKUP_DATABASE_PASSWORD'] %>
