default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: postcode_lookup_development

test:
  <<: *default
  database: postcode_lookup_test

production:
  <<: *default
  database: <%= Diplomat.get('greens/postcode/db/name') %>
  username: <%= Diplomat.get('greens/postcode/db/username') %>
  password: <%= Diplomat.get('greens/postcode/db/password') %>
